// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates
// SPDX-License-Identifier: Apache-2.0

import assert from 'node:assert/strict';
import os from 'node:os';
import path from 'node:path';
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { requestJson, requestOpenApiJson, buildSignedRequestHeaders } from '../src/core/http';
import { resolveServiceConfig } from '../src/core/service-config';
import { resolveRuntimeConfig } from '../src/core/config';
import { formatCliConfigEntries, listCliConfigKeys, loadCliConfigSync, saveCliConfig } from '../src/core/user-config';

const originalFetch = globalThis.fetch;
const originalConfigPath = process.env.VIKING_CONFIG_PATH;
const originalApiKey = process.env.VIKING_API_KEY;

async function main(): Promise<void> {
  await testManualConfigOnlyAffectsExpectedRequestPlane();
  await testApiKeyOnlyAuthUsesBearerHeaders();
  await testSkipsHeaderWhenMissing();
  await testSkipsHeaderWhenConfigIsInvalidJson();
  await testHiddenKeysStayOutOfCliDisplayAndAutoGeneratedConfig();
}

async function testManualConfigOnlyAffectsExpectedRequestPlane(): Promise<void> {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'viking-http-header-'));
  try {
    const configPath = path.join(tempDir, '.viking', 'config.json');
    await mkdir(path.dirname(configPath), { recursive: true });
    await writeFile(
      configPath,
      JSON.stringify({
        host: 'search.example.com',
        'x-tt-backend': 'stable-backend'
      }),
      'utf8'
    );

    process.env.VIKING_CONFIG_PATH = configPath;

    const serviceConfig = resolveServiceConfig(baseServiceConfigInput());
    assert.equal(serviceConfig.xTtBackend, 'stable-backend');
    assert.equal(serviceConfig.dataPlaneHost, 'search.example.com');

    let openApiHeader: string | null = null;
    let openApiHostHeader: string | null = null;
    globalThis.fetch = async (_input: string | URL | Request, init?: RequestInit): Promise<Response> => {
      openApiHeader = readHeader(init?.headers, 'x-tt-backend');
      openApiHostHeader = readHeader(init?.headers, 'host');
      return new Response('{}', { status: 200, headers: { 'content-type': 'application/json' } });
    };

    await requestOpenApiJson(serviceConfig, 'POST', '/api/v1/ListDataset', { ProjectName: 'demo-project' });
    assert.equal(openApiHeader, 'stable-backend');
    assert.equal(openApiHostHeader, 'open.example.com');

    const runtimeConfig = resolveRuntimeConfig({
      ...baseRuntimeConfigInput(),
      applicationId: 'app-1',
      datasetId: 'dataset-1'
    });
    const runtimeHeaders = buildSignedRequestHeaders(
      runtimeConfig,
      'POST',
      new URL('https://data.example.com/api/v1/application/app-1/search'),
      '{}',
      { 'content-type': 'application/json' }
    );
    assert.equal(runtimeHeaders['x-tt-backend'], undefined);
    assert.equal(runtimeHeaders.host, 'search.example.com');
  } finally {
    globalThis.fetch = originalFetch;
    await rm(tempDir, { recursive: true, force: true });
  }
}

async function testApiKeyOnlyAuthUsesBearerHeaders(): Promise<void> {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'viking-http-header-'));
  try {
    const configPath = path.join(tempDir, '.viking', 'config.json');
    await mkdir(path.dirname(configPath), { recursive: true });
    await writeFile(configPath, '{}', 'utf8');
    process.env.VIKING_CONFIG_PATH = configPath;
    process.env.VIKING_API_KEY = 'runtime-api-key';

    const serviceConfig = resolveServiceConfig({
      controlPlaneBaseUrl: 'https://open.example.com',
      dataPlaneBaseUrl: 'https://data.example.com',
      region: 'cn-beijing',
      projectName: 'demo-project',
      timeoutMs: 5000
    });
    assert.equal(serviceConfig.apiKey, 'runtime-api-key');
    assert.equal(serviceConfig.authSource, 'api-key');

    const explicitAkSkConfig = resolveServiceConfig({
      controlPlaneBaseUrl: 'https://open.example.com',
      dataPlaneBaseUrl: 'https://data.example.com',
      apiKey: 'runtime-api-key',
      accessKeyId: 'flag-ak',
      secretKey: 'flag-sk',
      region: 'cn-beijing',
      projectName: 'demo-project',
      timeoutMs: 5000
    });
    assert.equal(explicitAkSkConfig.apiKey, undefined);
    assert.equal(explicitAkSkConfig.authSource, 'flag');

    let authorizationHeader: string | null = null;
    let hostHeader: string | null = null;
    globalThis.fetch = async (_input: string | URL | Request, init?: RequestInit): Promise<Response> => {
      authorizationHeader = readHeader(init?.headers, 'authorization');
      hostHeader = readHeader(init?.headers, 'host');
      return new Response('{}', { status: 200, headers: { 'content-type': 'application/json' } });
    };

    await requestJson(serviceConfig, 'POST', '/api/v1/application/app-1/search', { query: { text: 'demo' } });
    assert.equal(authorizationHeader, 'Bearer runtime-api-key');
    assert.equal(hostHeader, null);
    await assert.rejects(
      requestOpenApiJson(serviceConfig, 'POST', '/api/v1/ListDataset', { ProjectName: 'demo-project' }),
      /control-plane/
    );

    const runtimeConfig = resolveRuntimeConfig({
      controlPlaneBaseUrl: 'https://open.example.com',
      dataPlaneBaseUrl: 'https://data.example.com',
      applicationId: 'app-1',
      datasetId: 'dataset-1',
      region: 'cn-beijing',
      timeoutMs: 5000,
      defaultPageSize: 10,
      outputDir: '.viking/reports'
    });
    const runtimeHeaders = buildSignedRequestHeaders(
      runtimeConfig,
      'POST',
      new URL('https://data.example.com/api/v1/application/app-1/search'),
      '{}',
      { 'content-type': 'application/json' }
    );
    assert.equal(runtimeHeaders.authorization, 'Bearer runtime-api-key');
    assert.equal(runtimeHeaders.host, undefined);
  } finally {
    globalThis.fetch = originalFetch;
    await rm(tempDir, { recursive: true, force: true });
  }
}

async function testSkipsHeaderWhenMissing(): Promise<void> {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'viking-http-header-'));
  try {
    const configPath = path.join(tempDir, '.viking', 'config.json');
    await mkdir(path.dirname(configPath), { recursive: true });
    await writeFile(
      configPath,
      JSON.stringify({
        host: 'search.example.com'
      }),
      'utf8'
    );

    process.env.VIKING_CONFIG_PATH = configPath;

    const serviceConfig = resolveServiceConfig(baseServiceConfigInput());
    assert.equal(serviceConfig.xTtBackend, undefined);

    let openApiHeader: string | null = null;
    globalThis.fetch = async (_input: string | URL | Request, init?: RequestInit): Promise<Response> => {
      openApiHeader = readHeader(init?.headers, 'x-tt-backend');
      return new Response('{}', { status: 200, headers: { 'content-type': 'application/json' } });
    };

    await requestOpenApiJson(serviceConfig, 'POST', '/api/v1/ListDataset', { ProjectName: 'demo-project' });
    assert.equal(openApiHeader, null);
  } finally {
    globalThis.fetch = originalFetch;
    await rm(tempDir, { recursive: true, force: true });
  }
}

async function testSkipsHeaderWhenConfigIsInvalidJson(): Promise<void> {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'viking-http-header-'));
  try {
    const configPath = path.join(tempDir, '.viking', 'config.json');
    await mkdir(path.dirname(configPath), { recursive: true });
    await writeFile(configPath, '{"x-tt-backend": ', 'utf8');

    process.env.VIKING_CONFIG_PATH = configPath;

    const serviceConfig = resolveServiceConfig(baseServiceConfigInput());
    assert.equal(serviceConfig.xTtBackend, undefined);

    let openApiHeader: string | null = 'unexpected';
    globalThis.fetch = async (_input: string | URL | Request, init?: RequestInit): Promise<Response> => {
      openApiHeader = readHeader(init?.headers, 'x-tt-backend');
      return new Response('{}', { status: 200, headers: { 'content-type': 'application/json' } });
    };

    await requestOpenApiJson(serviceConfig, 'POST', '/api/v1/ListDataset', { ProjectName: 'demo-project' });
    assert.equal(openApiHeader, null);
  } finally {
    globalThis.fetch = originalFetch;
    await rm(tempDir, { recursive: true, force: true });
  }
}

async function testHiddenKeysStayOutOfCliDisplayAndAutoGeneratedConfig(): Promise<void> {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'viking-http-header-'));
  try {
    const configPath = path.join(tempDir, '.viking', 'config.json');
    await mkdir(path.dirname(configPath), { recursive: true });
    process.env.VIKING_CONFIG_PATH = configPath;

    assert.equal(listCliConfigKeys().includes('host'), false);
    assert.equal(listCliConfigKeys().includes('x-tt-backend'), false);

    await saveCliConfig({
      activeProfile: 'default',
      profiles: {
        default: {
          baseUrl: 'https://data.example.com',
          controlPlaneBaseUrl: 'https://open.example.com',
          dataPlaneBaseUrl: 'https://data.example.com',
          region: 'cn-beijing',
          projectName: 'demo-project',
          timeoutMs: 5000
        }
      }
    });

    const autoGeneratedRaw = await readFile(configPath, 'utf8');
    assert.equal(autoGeneratedRaw.includes('"host"'), false);
    assert.equal(autoGeneratedRaw.includes('"x-tt-backend"'), false);

    await writeFile(
      configPath,
      JSON.stringify({
        host: 'search.example.com',
        'x-tt-backend': 'stable-backend',
        region: 'cn-beijing'
      }),
      'utf8'
    );

    const loaded = loadCliConfigSync(configPath);
    const visibleEntries = formatCliConfigEntries(loaded, false);
    assert.equal(visibleEntries.some(entry => entry.key === 'host'), false);
    assert.equal(visibleEntries.some(entry => entry.key === 'x-tt-backend'), false);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
}

function baseServiceConfigInput() {
  return {
    controlPlaneBaseUrl: 'https://open.example.com',
    dataPlaneBaseUrl: 'https://data.example.com',
    accessKeyId: 'test-ak',
    secretKey: 'test-sk',
    region: 'cn-beijing',
    projectName: 'demo-project',
    timeoutMs: 5000
  };
}

function baseRuntimeConfigInput() {
  return {
    controlPlaneBaseUrl: 'https://open.example.com',
    dataPlaneBaseUrl: 'https://data.example.com',
    accessKeyId: 'test-ak',
    secretKey: 'test-sk',
    region: 'cn-beijing',
    timeoutMs: 5000,
    defaultPageSize: 10,
    outputDir: '.viking/reports'
  };
}

function readHeader(headers: HeadersInit | undefined, key: string): string | null {
  if (!headers) return null;
  const normalized = new Headers(headers);
  return normalized.get(key);
}

main()
  .then(() => {
    console.log('http header config tests passed');
  })
  .catch(error => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(() => {
    globalThis.fetch = originalFetch;
    if (originalConfigPath === undefined) {
      delete process.env.VIKING_CONFIG_PATH;
    } else {
      process.env.VIKING_CONFIG_PATH = originalConfigPath;
    }
    if (originalApiKey === undefined) {
      delete process.env.VIKING_API_KEY;
    } else {
      process.env.VIKING_API_KEY = originalApiKey;
    }
  });
